ulimit -s unlimited
./monitor ./heap ./testfiles/*.txt
./monitor ./merge ./testfiles/*.txt
./monitor ./tim ./testfiles/*.txt
./monitor ./quick ./testfiles/*.txt
./monitor ./tournament ./testfiles/*.txt
./monitor ./intro ./testfiles/*.txt
./monitor ./comb ./testfiles/*.txt
./monitor ./library ./testfiles/*.txt
./monitor ./shaker ./testfiles/*.txt
./monitor ./insert ./testfiles/*.txt
./monitor ./select ./testfiles/*.txt
./monitor ./bubble ./testfiles/*.txt